name: Сообщение об ошибке
title: "[Ошибка] "
description: Сообщите о проблеме, с которой вы столкнулись

body:
  - type: markdown
    attributes:
      value: |
        ## Перед созданием обращения проверьте:
        1. Укажите короткий и понятный заголовок, чтобы проблему было легко найти.
        2. Убедитесь, что похожей проблемы нет среди [существующих обращений](https://github.com/makriq3/FlClash/issues?q=is%3Aissue).
        3. Опишите проблему подробно по шаблону, иначе обращение может быть закрыто без разбора.
  - type: textarea
    id: description
    attributes:
      label: Описание проблемы
      description: Подробно опишите проблему и, если нужно, приложите скриншоты
    validations:
      required: true
  - type: textarea
    attributes:
      label: Версия приложения
      description: Укажите точную версию FlClash
    validations:
      required: true
  - type: textarea
    attributes:
      label: Шаги для воспроизведения
      description: Опишите шаги, с помощью которых можно воспроизвести проблему
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Операционная система
      options:
        - Android
        - Windows
        - MacOS
        - Linux
    validations:
      required: true
  - type: input
    attributes:
      label: Версия ОС
      description: Укажите версию системы, а для Linux дополнительно рабочее окружение и оконную систему
    validations:
      required: true
  - type: textarea
    attributes:
      label: Логи
      description: Вставьте сюда содержимое логов. Не прикладывайте файл, а вставьте текст. Для полноты переключите уровень логов на `debug`.
    validations:
      required: true
