name: Запрос функции
title: "[Функция] "
description: Предложите новую функцию или улучшение

body:
  - type: markdown
    attributes:
      value: |
        ## Перед созданием запроса на функцию проверьте:
        1. Укажите короткий и понятный заголовок.
        2. Убедитесь, что похожего запроса нет среди [существующих обращений](https://github.com/makriq-org/FlClash/issues?q=is%3Aissue).
        3. Опишите предложение подробно по шаблону, иначе обращение может быть закрыто.

  - type: textarea
    id: description
    attributes:
      label: Описание функции
      description: Чётко и подробно опишите, что именно вы предлагаете
    validations:
      required: true
  - type: textarea
    attributes:
      label: Сценарий использования
      description: Опишите, где и зачем нужна эта функция
    validations:
      required: true
  - type: checkboxes
    id: os-labels
    attributes:
      label: Целевые платформы
      description: Выберите платформы, к которым относится запрос
      options:
        - label: Android
        - label: Windows
        - label: MacOS
        - label: Linux
    validations:
      required: true
